# Generated by Django 4.2.9 on 2025-03-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id_instructor', models.AutoField(primary_key=True, serialize=False)),
                ('n_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('v_specialty', models.CharField(max_length=255)),
                ('v_bio', models.TextField()),
            ],
            options={
                'db_table': 'INSTRUCTOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('n_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('d_starting_date', models.DateField()),
                ('d_join_date', models.DateField()),
            ],
            options={
                'db_table': 'STUDENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('', 'User Role'), ('instructor', 'Instructor'), ('student', 'Student'), ('admin', 'Admin')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
