# Generated by Django 4.2.20 on 2025-04-05 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.BooleanField()),
                ("is_active", models.BooleanField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChapterEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "CHAPTER_EVALUATION",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ChapterExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "CHAPTER_EXERCISE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DifficultyLevel",
            fields=[
                (
                    "id_difficultylevel",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("v_title", models.CharField(max_length=20)),
                ("v_description", models.TextField()),
            ],
            options={
                "db_table": "DIFFICULTY_LEVEL",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                ("id_evaluation", models.AutoField(primary_key=True, serialize=False)),
                ("f_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("d_deadline", models.DateField()),
            ],
            options={
                "db_table": "EVALUATION",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EvaluationExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "EVALUATION_EXERCISE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                ("id_exercise", models.AutoField(primary_key=True, serialize=False)),
                ("f_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("d_deadline", models.DateField()),
                ("n_max_attempts", models.PositiveIntegerField(default=3)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "EXERCISE",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                ("id_instructor", models.AutoField(primary_key=True, serialize=False)),
                ("n_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("v_specialty", models.CharField(max_length=255)),
                ("v_bio", models.TextField()),
            ],
            options={
                "db_table": "INSTRUCTOR",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LearningChapter",
            fields=[
                (
                    "id_learningchapter",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("d_created_at", models.DateField()),
                ("v_content", django_quill.fields.QuillField()),
                ("d_deadline", models.DateField(blank=True, null=True)),
                ("f_weight", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "db_table": "LEARNING_CHAPTER",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MultipleOption",
            fields=[
                ("id_option", models.AutoField(primary_key=True, serialize=False)),
                ("b_iscorrect", models.BooleanField()),
                ("v_option", models.TextField()),
            ],
            options={
                "db_table": "MULTIPLE_OPTION",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id_student", models.AutoField(primary_key=True, serialize=False)),
                (
                    "n_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("d_starting_date", models.DateField()),
                ("d_join_date", models.DateField()),
            ],
            options={
                "db_table": "STUDENT",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("", "User Role"),
                            ("instructor", "Instructor"),
                            ("student", "Student"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
