# Generated by Django 4.2.9 on 2025-03-28 22:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'CHAPTER_EVALUATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChapterExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'CHAPTER_EXERCISE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id_difficultylevel', models.AutoField(primary_key=True, serialize=False)),
                ('v_title', models.CharField(max_length=20)),
                ('v_description', models.TextField()),
            ],
            options={
                'db_table': 'DIFFICULTY_LEVEL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.AutoField(primary_key=True, serialize=False)),
                ('f_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('d_deadline', models.DateField()),
            ],
            options={
                'db_table': 'EVALUATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'EVALUATION_EXERCISE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id_exercise', models.AutoField(primary_key=True, serialize=False)),
                ('f_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('d_deadline', models.DateField()),
                ('n_max_attempts', models.PositiveIntegerField(default=3)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'EXERCISE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LearningChapter',
            fields=[
                ('id_learningchapter', models.AutoField(primary_key=True, serialize=False)),
                ('d_created_at', models.DateField()),
                ('v_content', ckeditor.fields.RichTextField()),
                ('d_deadline', models.DateField(blank=True, null=True)),
                ('f_weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'LEARNING_CHAPTER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleOption',
            fields=[
                ('id_option', models.AutoField(primary_key=True, serialize=False)),
                ('b_iscorrect', models.BooleanField()),
                ('v_option', models.TextField()),
            ],
            options={
                'db_table': 'MULTIPLE_OPTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('created', models.DateField()),
                ('starting_at', models.DateField()),
                ('finishing_at', models.DateField()),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('v_answer', models.TextField()),
                ('n_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('b_iscorrect', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.exercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapp.student')),
            ],
        ),
    ]
