# Generated by Django 4.2.9 on 2025-03-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chapterevaluation_chapterexercise_difficultylevel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningchapter',
            options={'managed': True},
        ),
    ]
