# Generated by Django 4.2.9 on 2025-04-02 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_learningchapter_options_studentcourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('d_begins', models.DateField(blank=True, null=True)),
                ('d_finish', models.DateField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(db_column='id_evaluation', on_delete=django.db.models.deletion.CASCADE, to='myapp.evaluation')),
                ('student', models.ForeignKey(db_column='id_student', on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
            options={
                'unique_together': {('student', 'evaluation')},
            },
        ),
    ]
