# Generated by Django 4.2.9 on 2025-04-02 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_studentevaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'managed': False},
        ),
    ]
