# Generated by Django 4.2.9 on 2025-04-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_course_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='COURSE',
        ),
    ]
