# Generated by Django 4.2.9 on 2025-04-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_course_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_began', models.DateTimeField()),
                ('d_finished', models.DateTimeField()),
                ('n_attempt_number', models.IntegerField()),
                ('answer', models.ForeignKey(db_column='id_answer', on_delete=django.db.models.deletion.RESTRICT, to='myapp.answer')),
                ('option', models.ForeignKey(db_column='id_option', on_delete=django.db.models.deletion.RESTRICT, to='myapp.multipleoption')),
            ],
            options={
                'unique_together': {('answer', 'option')},
            },
        ),
    ]
