# Generated by Django 4.2.9 on 2025-04-02 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_attempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'managed': False},
        ),
    ]
