# Generated by Django 4.2.9 on 2025-04-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_studentcourse_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentcourse',
            table='STUDENT_COURSE',
        ),
    ]
