# Generated by Django 4.2.9 on 2025-04-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_studentcourse_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentevaluation',
            options={'managed': False},
        ),
    ]
