# Generated by Django 4.2.9 on 2025-04-04 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_answer_v_answer_alter_studentevaluation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermultipleoption',
            name='answer',
            field=models.ForeignKey(db_column='id_answer', on_delete=django.db.models.deletion.CASCADE, to='myapp.answer'),
        ),
        migrations.AlterField(
            model_name='answermultipleoption',
            name='option',
            field=models.ForeignKey(db_column='id_option', on_delete=django.db.models.deletion.CASCADE, to='myapp.multipleoption'),
        ),
    ]
