# Generated by Django 4.2.9 on 2025-04-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_answermultipleoption_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='submitted_at',
        ),
    ]
