# Generated by Django 4.2.9 on 2025-04-04 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_answer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='ANSWER',
        ),
        migrations.AlterModelTable(
            name='answermultipleoption',
            table='ANSWER_MULTIPLE_OPTION',
        ),
        migrations.AlterModelTable(
            name='attempt',
            table='ATTEMPT',
        ),
        migrations.AlterModelTable(
            name='chapterstudent',
            table='CHAPTER_STUDENT',
        ),
        migrations.AlterModelTable(
            name='courselearnchapter',
            table='COURSE_LEARN_CHAPTER',
        ),
    ]
