# Generated by Django 4.2.9 on 2025-04-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_answer_table_alter_answermultipleoption_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterstudent',
            options={'managed': True},
        ),
    ]
