# Generated by Django 4.2.9 on 2025-04-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_chapterstudent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapterstudent',
            options={'managed': False},
        ),
    ]
