# Generated by Django 4.2.9 on 2025-04-05 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_chapterstudent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='USER_PROFILE',
        ),
    ]
